version: 2.1
executors:
  java-executor:
    docker:
      - image: cimg/openjdk:11.0.3
    working_directory: ~/project

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Building Debezium server pubsub module
          command: ./mvnw -Dquick -DskipIT package -pl debezium-server/debezium-server-pubsub -am
      - run:
          name: Copying select Debezium modules to docker workspace
          command: cp debezium-server/debezium-server-pubsub/target/debezium-server-pubsub-*-SNAPSHOT.jar docker/lib/debezium-server-pubsub-1.9.0.Final.jar
      - run:
          name: Building patched Debezium docker image
          command: cd docker && docker build . -t paritiio/debezium-server:1.9-1
      - setup_remote_docker
      - run:
          name: Authenticating with Docker hub
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Publishing image to docker
          command: docker push paritiio/debezium-server:1.9-1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context:
            - Docker Access
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
